image: node:latest
stages:
  - install
  - validate
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: validate
  script:
    - npm run test

lint:
  stage: validate
  script:
    - npm run lint

format:
  stage: validate
  script:
    - npm run format:write

build:
  stage: build
  script:
    - npm run build
  only: [main]
  artifacts:
    paths:
      - out/

deploy:
  stage: deploy
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  only: [main]
