name: mctw-tdw-mp1-luis
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
      - run: npm ci
  build:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
      -  uses: actions/cache@v2
         env:
          cache-name: cache-node-modules
         with:
          path: node_modules
          key: >-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
      - env:
          CONTENTFUL_ACCESS_TOKEN: '${{ secrets.CONTENTFUL_ACCESS_TOKEN }}'
          CONTENTFUL_SPACE_ID: '${{ secrets.CONTENTFUL_SPACE_ID }}'
      - run: npm run build
      - uses: actions/cache@v2
        with:
          path: out
          key: '${{ github.run_id }}'
  deploy:
    needs:
      - install
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: >-
            ${{ runner.os }}-build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v2
        with:
          path: out
          key: '${{ github.run_id }}'
      - env:
          NETLIFY_AUTH_TOKEN: '${{ secrets.NETLIFY_AUTH_TOKEN }}'
          NETLIFY_SITE_ID: '${{ secrets.NETLIFY_SITE_ID }}'
          run: >-
            npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth
            $NETLIFY_AUTH_TOKEN --prod
